version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test_api
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
