#!/bin/bash
cd /home/ec2-user/test_api
sudo npm install
sudo systemctl enable test_api.service
sudo systemctl start test_api.service
#so that the api updates with changes- need a better way
sudo systemctl restart test_api.service